# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'paradisepdreg.azurecr.io/paradisepdreg/fulfillorderack:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker login paradisepdreg.azurecr.io -u ParadisePDReg -p w9/8aFlFAk6iara5JSQW32OKHFJ0z4PI
  displayName: 'Login'

- script: docker push $(imageName)
  displayName: 'Push to registy'
